markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Lowe Thiderman
url: http://thiderman.org
description: A fantastic blog that is fantastic.
twitter: thiderman
github: thiderman
gravatar_url: http://gravatar.com/avatar/e6b88cb7759b82c82b26fa01130aa670.png
