markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Lowe Thiderman
url: http://thiderman.org
description: A fantastic blog that is fantastic.
twitter: thiderman
github: thiderman
gravatar_url: https://avatars2.githubusercontent.com/u/155394
